### ISSUE TITLE
Results limited to 100 (or to 1st page of html table)

### ISSUE THREAD

**Issue by afftx-christianroy** [imkeller/immunotation#1]
Fantastic package.  Very useful!

In working with it, I noticed that for some functions, queries with results >100 get trimmed.  Compare:

```r
hla_a_3217 <-
  immunotation::query_allele_frequencies(
    hla_locus = "A",
    hla_sample_size_pattern = "bigger_than",
    hla_sample_size = 10000,
    standard = "g",
    hla_population = 3217#USA NMDP Chinese
    )
```

to the results shown on the on [allelefrequences.net](http://www.allelefrequencies.net/hla6006a.asp?hla_locus_type=Classical&hla_locus=A&hla_allele1=&hla_allele2=&hla_selection=&hla_pop_selection=&hla_population=3217&hla_country=United+States&hla_dataset=&hla_region=North+America&hla_ethnic=&hla_study=&hla_order=order_2&hla_sample_size_pattern=equal&hla_sample_size=&hla_sample_year_pattern=equal&hla_sample_year=&hla_level_pattern=equal&hla_level=&standard=g&hla_show=%3E).  Looks like there should be 133 records.

Maybe loop through when multiple pages are returned in the url?  e.g. `hla6006a.asp?page=2`

Also, any way to return results sorted according to `hla_order`?  Option in automated access described [here](http://www.allelefrequencies.net/extaccess.asp).

**Comment by imkeller** [comment]
The problem with reading multiple pages should be fixed now. Please install the latest version from github. The new version will be available on Bioconductor soon.

Regarding sorting: could you do this in R after retrieving the output table?
