### ISSUE TITLE
error when using two-word Country names 

### ISSUE THREAD

**Issue by AGImkeller** [imkeller/immunotation#2]
`query_allele_frequencies(
    hla_locus = "C",
    hla_selection = NA,
    hla_population = NA,
    hla_country = "United States",
    hla_region = NA,
    hla_ethnic = NA,
    hla_sample_size_pattern = NA,
    hla_sample_size = NA,
    standard = "a"
)`

Returns:
```
Error in getURL(url, read_method = "html") : 'getURL()' failed:
URL: http://www.allelefrequencies.net/hla6006a.asp?hla_locus_type=Classical&hla_locus=C&hla_selection=&hla_population=&hla_country=United States&hla_dataset=&hla_region=&hla_ethnic=&hla_study=&hla_order=order_1&hla_sample_size_pattern=&hla_sample_size=&standard=a
error: URL using bad/illegal format or missing URL
```

**Comment by imkeller** [comment]
This should be fixed now. Please install the latest version from github. The new version will be available on Bioconductor soon.
